services:
  db:
    image: postgres:15-alpine
    container_name: quickapi-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: quickapi
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: quickapi-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quickapi-api
    depends_on:
      - db
      - redis
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5148:80"

volumes:
  db_data:
